contact_links:
  - name: Usage question & discussion
    url: https://github.com/Marcono1234/jtreesitter-type-gen/discussions
    about: Ask usage questions and discuss this project in GitHub Discussions.
